include(${CMAKE_LIB_DIR}/Utils.cmake)

message("POST OPERATIONS")
set(HTML_REPORT_DIR ${CMAKE_CURRENT_SOURCE_DIR}/coverage_report)
set(EXECUTABLE_FILE ${CMAKE_CURRENT_SOURCE_DIR}/${PROJECT_NAME}.exe)
message("EXECUTABLE_FILE: ${EXECUTABLE_FILE}")
message("TESTED_SOURCE_DIR: ${TESTED_SOURCE_DIR}")
message("HTML_REPORT_DIR: ${HTML_REPORT_DIR}")
generate_coverage_report(${TESTED_SOURCE_DIR} ${HTML_REPORT_DIR} ${EXECUTABLE_FILE})